export default {
  TITLE: 'Blog El que penses compta!',
  ADD_MULTIPLE_DOCS: 'Penjar múltiples textos',
  ADD_SINGLE_DOC: 'Penjar 1 text',
  SEARCH_PLACEHOLDER: 'títol, descripció, nom ...',
  SHOW_ALL: 'Mostrar tot',
  GRADE: 'Filtrar per curs',
  GRADE_2: '2n Primària',
  GRADE_4: '4n Primària',
  GRADE_8: '2n ESO',
  FIRST_STEP_SINGLE: 'Posa les teves dades',
  SECOND_STEP_SINGLE: 'Penja una foto del teu text',
  THIRD_STEP_SINGLE: 'Afegeix un títol y una descripció (opcional)',
  FOURTH_STEP_SINGLE: 'Determina l\'accés a les teves dades',
  FIRST_STEP_MULTIPLE: 'Posa les teves dades',
  SECOND_STEP_MULTIPLE: 'Afegeix TOTS els textos abans de premer "següent"',
  THIRD_STEP_MULTIPLE: 'Determina l\'accés a les dades dels alumnes',
  LABEL_NAME_INPUT: 'Nom*',
  LABEL_SURNAME_INPUT: 'Cognoms*',
  LABEL_SCHOOLS_SELECT: 'Centre*',
  LABEL_GRADES_SELECT: 'Curs*',
  LABEL_CLASSES_SELECT: 'Classe*',
  LABEL_TITLE_INPUT: 'Títol',
  LABEL_DESCRIPTION_INPUT: 'Descripció',
  WARNING_SINGLE_FORM: 'Vull que el meu nom i cognoms siguin públics',
  WARNING_MULTIPLE_FORM: 'Vull que el nom i cognom dels alumnes siguin públics',
  UPLOAD_PHOTO: 'Fes una foto o tria la imatge del text',
  NEXT: 'Següent',
  SAVE: 'Desar (no es pot desfer)',
  BACK: 'Tornar',
  ADD_STUDENT_DIALOG_TITLE: 'Afegir alumne',
  CANCEL: 'Cancel·lar',
  ADD_STUDENT: 'Afegir',
  LOADING_STUDENT_DATA: 'Carregant',
  FORM_SAVED: 'Text penjat!',
  SEE: 'Veure la publicació'
}
