export default {
  TITLE: 'Ahora la escritura',
  ADD_MULTIPLE_DOCS: 'Añadir varios documentos',
  ADD_SINGLE_DOC: 'Añadir un documento',
  SEARCH_PLACEHOLDER: 'título, descripción, nombre ...',
  SHOW_ALL: 'Mostrar todos',
  GRADE: 'Filtrar por curso',
  GRADE_2: '2º Primaria',
  GRADE_4: '4º Primaria',
  GRADE_8: '2º ESO',
  FIRST_STEP_SINGLE: 'Datos personales',
  SECOND_STEP_SINGLE: 'Sube una foto de tu texto',
  THIRD_STEP_SINGLE: 'Título y descripción (Opcionales)',
  FOURTH_STEP_SINGLE: 'Quieres compartir tus datos?!',
  FIRST_STEP_MULTIPLE: 'Datos del profesor/ar y de la clase',
  SECOND_STEP_MULTIPLE: 'Textos de los alumnos',
  THIRD_STEP_MULTIPLE: 'Compartir datos de los alumnos',
  LABEL_NAME_INPUT: 'Nombre',
  LABEL_SURNAME_INPUT: 'Apellidos',
  LABEL_SCHOOLS_SELECT: 'Escuela',
  LABEL_GRADES_SELECT: 'Curso',
  LABEL_CLASSES_SELECT: 'Clase',
  LABEL_TITLE_INPUT: 'Título',
  LABEL_DESCRIPTION_INPUT: 'Descripción',
  WARNING_SINGLE_FORM: 'Acepto compartir mis datos personales con el retos de mis compañeros',
  UPLOAD_PHOTO: 'Elige o haz una foto',
  NEXT: 'Siguiente',
  SAVE: 'Guardar',
  BACK: 'Volver',
  ADD_STUDENT_DIALOG_TITLE: 'Agregar alumno',
  CANCEL: 'Cancelar',
  ADD_STUDENT: 'Añadir',
  LOADING_STUDENT_DATA: 'Cargando',
  FORM_SAVED: 'Texto guardado',
  SEE: 'Ver'
}
