export default {
  TITLE: 'Blog Lo que piensas ¡cuenta!',
  ADD_MULTIPLE_DOCS: 'Subir múltiples textos',
  ADD_SINGLE_DOC: 'Subir 1 texto',
  SEARCH_PLACEHOLDER: 'título, descripción, nombre ...',
  SHOW_ALL: 'Mostrar todo',
  GRADE: 'Filtrar por curso',
  GRADE_2: '2º Primaria',
  GRADE_4: '4º Primaria',
  GRADE_8: '2º ESO',
  FIRST_STEP_SINGLE: 'Pon tus datos',
  SECOND_STEP_SINGLE: 'Sube una foto de tu texto',
  THIRD_STEP_SINGLE: 'Título y descripción (opcional)',
  FOURTH_STEP_SINGLE: 'Determina el acceso a tus datos (nombre y apellidos)',
  FIRST_STEP_MULTIPLE: 'Pon tus datos',
  SECOND_STEP_MULTIPLE: 'Añade TODOS los textos antes de clicar "siguiente"',
  THIRD_STEP_MULTIPLE: 'Determina el acceso a los datos de los alumnos',
  LABEL_NAME_INPUT: 'Nombre*',
  LABEL_SURNAME_INPUT: 'Apellidos*',
  LABEL_SCHOOLS_SELECT: 'Centro*',
  LABEL_GRADES_SELECT: 'Curso*',
  LABEL_CLASSES_SELECT: 'Clase*',
  LABEL_TITLE_INPUT: 'Título',
  LABEL_DESCRIPTION_INPUT: 'Descripción',
  WARNING_SINGLE_FORM: 'Quiero que mi nombre y apellidos sean públicos',
  WARNING_MULTIPLE_FORM: 'Quiero que el nombre y apellidos de los alumnos sean públicos',
  UPLOAD_PHOTO: 'Haz una foto o selecciona la imagen del texto',
  NEXT: 'Siguiente',
  SAVE: 'Guardar (no se puede deshacer)',
  BACK: 'Volver',
  ADD_STUDENT_DIALOG_TITLE: 'Agregar alumno',
  CANCEL: 'Cancelar',
  ADD_STUDENT: 'Añadir',
  LOADING_STUDENT_DATA: 'Cargando',
  FORM_SAVED: '¡Texto subido!',
  SEE: 'Ver la publicación'
}
